[package]
name = "clap_tests"
version = "0.1.0"
authors = ["Christian Gröling"]
edition = "2021"
default-run="clap_tests"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.22", features = ["derive", "cargo"] }
